version: "3"
services:
  # ====================================================================================================================
  # POSTGRES SERVER
  # ====================================================================================================================
  postgres:
    image: postgres:12-alpine
    container_name: dev-postgresql-12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234567
      POSTGRES_DB: dscatalog
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - dev-network
  # ====================================================================================================================
  # PGADMIN
  # ====================================================================================================================
  pgadmin:
    image: dpage/pgadmin4
    container_name: dev-pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - dev-network
  # ======================================================================================================================
  # VOLUME
  # ======================================================================================================================      
volumes:
  postgres-data:   # Nome do volume Docker
  # ======================================================================================================================
  # APP
  # ======================================================================================================================
  # ======================================================================================================================
  # REDE
  # ======================================================================================================================
networks:
  dev-network:
    driver: bridge